source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.2'
gem 'pg', '~> 0.18'
gem 'puma', '~> 4.3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'coffee-rails'

group :development do
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :test do
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'rspec-retry'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
end

gem 'dotenv-rails', groups: [:development, :test]
gem 'administrate'
gem 'telegram-bot-ruby'

gem 'redis'
gem 'sidekiq'

gem 'pry'
gem 'attachinary'
gem 'cloudinary'
gem 'responders'

gem 'pg_search'
gem 'kaminari'
