---
- hosts: all
  gather_facts: no

  tasks:
    - apt:
        update_cache: true
        name:
          - python3-pip
      become: true

    - pip:
        name:
          - docker
      become: true

    - docker_network:
        name: "{{ catalog_with_telegram_bot_docker_network }}"
      tags: docker_network
      become: true

    - name: create app dir
      file:
        path: "{{ catalog_with_telegram_bot_app_path }}"
        state: directory
      become: true

    - template:
        src: environment.j2
        dest: "{{ catalog_with_telegram_bot_env_file }}"
      tags: env
